CREATE TABLE users (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    activated BOOLEAN DEFAULT FALSE,
    pass VARCHAR(255) NOT NULL
);

CREATE TABLE houses (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    label VARCHAR(1000) NOT NULL,
    image VARCHAR(1000) NOT NULL,
    body VARCHAR(1000) NOT NULL,
    price NUMERIC NOT NULL,
    owner JSON NOT NULL
);

CREATE TABLE tokens (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    userId BIGSERIAL NOT NULL REFERENCES users(id),
    refreshToken VARCHAR(1000) NOT NULL
);